name: inbloc_clean
description: This project contains the basic login operation that is built with tdd Bloc & cubit.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5


  flutter:
    sdk: flutter

  dio: ^5.3.3
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  go_router: ^11.1.2
  http: ^1.1.0
  shared_preferences: ^2.2.1
  freezed_annotation: ^2.4.1
  freezed: ^2.4.3
  internet_connection_checker: ^0.0.1+3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  

flutter:
  uses-material-design: true


